#!/bin/bash

VID_DIR='../imgs/contagion/videos'
ATTACKS='random closeness betweenness hits pagerank clustering'
OUT_DIR=$VID_DIR/mp4
DIM='small big'
TYPE='simple complex'

SIMPLE_SMALL_P='0_15'
SMALL_T='1_5 1_7 1_35'
SIMPLE_BIG_P='0_4'
BIG_T='1_8 1_11 1_22'


function err_exit() {
	RED='\033[0;31m'
	echo -e "${RED}Usage: ./make_contagion_videos"
	exit 1
}


function build_video() {
    filename=$1
    ffmpeg -r 2 -i "$VID_DIR/${filename}_%05d.png" -c:v libx264 -vf 'fps=60,format=yuv420p' "$OUT_DIR/$filename.mp4"
}


# check there are no command line arguments
if [ $# -gt 0 ]; then
	err_exit
fi

# clean old videos
rm -f $OUT_DIR/*	

# iterate all possible name combinations
for d in $DIM; do
    for t in $TYPE; do
        for a in $ATTACKS; do
            if [[ "$t" == "simple" ]]; then
                if [[ "$d" == "big" ]]; then
                    filename="${d}_${t}_${SIMPLE_SMALL_P}_${a}"
                    build_video $filename
                else
                    filename="${d}_${t}_${SIMPLE_BIG_P}_${a}"
                    build_video $filename
                fi
            else
                if [[ "$d" == "big" ]]; then
                    for th in $BIG_T; do
                        filename="${d}_${t}_${th}_${a}"
                        build_video $filename
                    done
                else
                    for th in $SMALL_T; do
                        filename="${d}_${t}_${th}_${a}"  
                        build_video $filename
                    done
                fi
            fi
        done
    done
done